version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./init-db/create-user.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      POSTGRES_USER: $POSTGRESDB_USER
      POSTGRES_PASSWORD: $POSTGRESDB_ROOT_PASSWORD
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d labs_amch_db -h localhost -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db: